CC = gcc -g
FLAGS = -Wall


helloworld:
		$(CC) $(FLAGS) main.c helloworld.c -o main
		

ls:
	ls -l

manprint:
	man printf

clearscreen:
	clear

tarshit:
	 tar cvzf oppgave1.tar.gz oppgave1


faen:
	rm -f *.o
	rm -f main
