CC = gcc -g
CFLAGS = -Wall

read:
	$(CC) $(CFLAGS) bank_read.c -o read_file

write:
	$(CC) $(CLFAGS) bank_write.c -o write_file

create:
	$(CC) $(CFLAGS) creat_file.c -o create_file

clean:
	rm -f read_file
	rm -f write_file
	rm -f create_file
	rm -f backup.bak